const A=window.Aegis;let S=A.load();const map=document.getElementById("map");const ctx=map.getContext("2d");
function size(){map.width=map.clientWidth*devicePixelRatio;map.height=map.clientHeight*devicePixelRatio}
function pos(n){return{x:n.x*map.width,y:n.y*map.height}}
function draw(){size();ctx.clearRect(0,0,map.width,map.height);for(const c of S.circuits){const a=S.nodes.find(n=>n.id===c.from),b=S.nodes.find(n=>n.id===c.to);if(!a||!b)continue;const pa=pos(a),pb=pos(b);ctx.strokeStyle=c.loop_factor>.4?"rgba(212,80,80,.55)":"rgba(126,224,214,.35)";ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke()}for(const n of S.nodes){const p=pos(n),r=(10+n.resilience*10)*devicePixelRatio;ctx.beginPath();ctx.fillStyle=n.vulnerability>.45?"#c45b5b":(n.cloak>.2?"#7ee0d6":"#d4b36a");ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.fillStyle="#f4efe6";ctx.font=(11*devicePixelRatio)+"px Georgia";ctx.fillText(n.name,p.x+r+4,p.y)}}
async function heartbeat(){const box=document.getElementById("heart");try{const r=await fetch("https://api.github.com/users/tariromasawi/repos?per_page=20");const repos=r.ok?await r.json():[];box.innerHTML=`<div class="item"><span class="badge">REPOS</span>${Array.isArray(repos)?repos.length:"n/a"} public</div><div class="item"><span class="badge">SIG</span>${(S.watch.signature||"").slice(0,16)}</div>`}catch{box.textContent="heartbeat limited (rate or offline)"}}
function paint(){draw();const scan=A.nimScan(S),eea=A.eeaAnalyze(),paths=A.ppmPredict();document.getElementById("status").textContent="WATCH "+S.watch.ticks+" · decoys "+S.watch.decoys+" · chain "+(S.chain||"").slice(0,10);const hrs=A.staleHours(S);document.getElementById("stale").textContent=hrs>12?"STALE WATCH — run TICK or wait for Action":"watch fresh";document.getElementById("protocols").innerHTML=Object.entries(A.PROTOCOLS).map(([k,v])=>`<div class="item"><span class="badge">${k}</span>${v}</div>`).join("");document.getElementById("feed").innerHTML=S.feed.map(f=>`<div class="item"><span class="badge">${f.type}</span>${f.summary}</div>`).join("")||"No events.";const ideas=A.isgGenerate(S);document.getElementById("ideas").innerHTML=ideas.slice(0,5).map((x,i)=>`<button data-i="${i}">${x.label}</button>`).join("");document.querySelectorAll("#ideas button").forEach((b,i)=>b.onclick=async()=>{S=await A.apply(S,ideas[i]);A.save(S);paint()});heartbeat()}
document.getElementById("scanBtn").onclick=()=>{A.log(S,"SCAN","NIM/EEA/PPM");A.save(S);paint()};
document.getElementById("watchBtn").onclick=async()=>{S=await A.tickWatch(S);A.save(S);paint()};
document.getElementById("cloakBtn").onclick=async()=>{S=await A.tickWatch(S);A.save(S);paint()};
document.getElementById("familyBtn").onclick=()=>{S=A.familyPack(S);A.save(S);paint()};
document.getElementById("prayBtn").onclick=()=>{S=A.attest(S,"prayed");A.save(S);paint()};
document.getElementById("restBtn").onclick=()=>{S=A.attest(S,"rested");A.save(S);paint()};
document.getElementById("ateBtn").onclick=()=>{S=A.attest(S,"ate");A.save(S);paint()};
document.getElementById("ingestBtn").onclick=()=>{A.log(S,"INSIGHT",document.getElementById("insight").value.slice(0,80));A.save(S);paint()};
document.getElementById("snapBtn").onclick=()=>{const b=new Blob([JSON.stringify(S,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="aegis-snapshot.json";a.click()};
document.getElementById("auditBtn").onclick=()=>{const b=new Blob([S.feed.map(f=>f.at+" "+f.type+" "+f.summary).join("\n")],{type:"text/plain"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="aegis-audit.txt";a.click()};
document.getElementById("notifyBtn").onclick=async()=>{if(!("Notification"in window))return;const p=await Notification.requestPermission();if(p==="granted")new Notification("Aegis watch armed",{body:"Local alerts only. Scheduled Action still needs GitHub."})};
fetch("./data/aegis-state.json").then(r=>r.ok?r.json():null).then(remote=>{if(remote?.watch?.ticks>(S.watch.ticks||0)){S.watch=Object.assign(S.watch,remote.watch);A.log(S,"WATCH","loaded scheduled file");A.save(S)}}).catch(()=>{}).finally(paint);
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
setInterval(async()=>{S=await A.tickWatch(S);A.save(S);paint()},180000);
