const A=window.Aegis;let S=A.load();const map=document.getElementById("map");const ctx=map.getContext("2d");
function size(){map.width=map.clientWidth*devicePixelRatio;map.height=map.clientHeight*devicePixelRatio}
function pos(n){return{x:n.x*map.width,y:n.y*map.height}}
function draw(){size();ctx.clearRect(0,0,map.width,map.height);for(const c of S.circuits){const a=S.nodes.find(n=>n.id===c.from),b=S.nodes.find(n=>n.id===c.to);if(!a||!b)continue;const pa=pos(a),pb=pos(b);ctx.strokeStyle=c.loop_factor>.4?"rgba(212,80,80,.55)":"rgba(126,224,214,.35)";ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke()}for(const n of S.nodes){const p=pos(n),r=(10+n.resilience*10)*devicePixelRatio;ctx.beginPath();ctx.fillStyle=n.vulnerability>.45?"#c45b5b":n.cloak>.2?"#7ee0d6":"#d4b36a";ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.fillStyle="#f4efe6";ctx.font=(11*devicePixelRatio)+"px Georgia";ctx.fillText(n.name,p.x+r+4,p.y)}}
function paint(){draw();const scan=A.nimScan(S),eea=A.eeaAnalyze(S),paths=A.ppmPredict(S);document.getElementById("status").textContent="WATCH "+S.watch.ticks+" · decoys "+S.watch.decoys;document.getElementById("scan").innerHTML=`<div class="item"><span class="badge">NIM</span> weak ${scan.weak.length} · potholes ${scan.potholes.length} · loops ${scan.loops.length}</div><div class="item"><span class="badge">EEA</span> fuels: ${eea.harvest.join(", ")}</div>`+paths.map(p=>`<div class="item"><span class="badge">PPM</span> ${p.id} ${p.via.join(" → ")}</div>`).join("");document.getElementById("feed").innerHTML=S.feed.map(f=>`<div class="item"><span class="badge">${f.type}</span>${f.summary}</div>`).join("")||"No events yet.";const ideas=A.isgGenerate(S,document.getElementById("insight").value);document.getElementById("ideas").innerHTML=ideas.slice(0,6).map((idea,i)=>`<button data-i="${i}">${idea.label}</button>`).join("");document.querySelectorAll("#ideas button").forEach((btn,i)=>{btn.onclick=async()=>{S=await A.apply(S,ideas[i]);A.save(S);paint()}})}
document.getElementById("scanBtn").onclick=()=>{A.log(S,"SCAN","NIM/EEA/PPM sweep");A.save(S);paint()};
document.getElementById("watchBtn").onclick=()=>{S=A.tickWatch(S);A.save(S);paint()};
document.getElementById("ingestBtn").onclick=()=>{A.log(S,"INSIGHT",document.getElementById("insight").value.slice(0,80));A.save(S);paint()};
fetch("./data/aegis-state.json").then(r=>r.ok?r.json():null).then(remote=>{if(remote?.watch?.ticks> (S.watch.ticks||0)){S.watch=remote.watch;A.log(S,"WATCH","loaded scheduled file");A.save(S)}}).catch(()=>{}).finally(paint);
setInterval(()=>{S=A.tickWatch(S);A.save(S);paint()},120000);
