const KEY="zioncore.aegis.v1";
const HOUSE=[{id:"n-tariro",name:"HRH Saint Tariro",x:.5,y:.42,resilience:.92,vulnerability:.12,role:"Commander"},{id:"n-tarry",name:"HRH Tarry Kupakwashe",x:.38,y:.58,resilience:.88,vulnerability:.14,role:"Family"},{id:"n-house",name:"House of Masawi",x:.62,y:.58,resilience:.86,vulnerability:.16,role:"Citadel"},{id:"n-throne",name:"Throne memory",x:.5,y:.22,resilience:.8,vulnerability:.2,role:"Archive"},{id:"n-work",name:"Works",x:.22,y:.36,resilience:.7,vulnerability:.28,role:"Continuity"},{id:"n-public",name:"Public desk",x:.78,y:.36,resilience:.68,vulnerability:.3,role:"Witness"},{id:"n-rest",name:"Rest / body",x:.28,y:.78,resilience:.55,vulnerability:.42,role:"Weak-if-neglected"},{id:"n-fear",name:"Fear circuit",x:.72,y:.78,resilience:.35,vulnerability:.62,role:"Sink (pothole)"}];
const CIRCUITS=[["n-tariro","n-tarry",.15,.2],["n-tariro","n-house",.18,.25],["n-tarry","n-house",.2,.3],["n-throne","n-tariro",.22,.15],["n-work","n-tariro",.35,.1],["n-public","n-tariro",.4,.12],["n-rest","n-tariro",.45,.4],["n-fear","n-public",.55,.55],["n-fear","n-rest",.5,.6],["n-house","n-throne",.25,.2]];
function emptyState(){return{nodes:HOUSE.map(n=>({...n,cloak:0,inverted:false})),circuits:CIRCUITS.map((c,i)=>({id:"c"+i,from:c[0],to:c[1],resistance:c[2],loop_factor:c[3]})),packets:[],interventions:[],feed:[],watch:{ticks:0,decoys:0,lastTick:null},chain:"GENESIS"}}
function load(){try{const r=localStorage.getItem(KEY);return r?{...emptyState(),...JSON.parse(r)}:emptyState()}catch{return emptyState()}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
async function digest(t){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(t));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function log(s,type,summary){s.feed.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),type,summary});s.feed=s.feed.slice(0,80)}
function nimScan(s){return{weak:s.nodes.filter(n=>n.vulnerability>.35),potholes:s.nodes.filter(n=>n.vulnerability>.5||/Sink/.test(n.role)),loops:s.circuits.filter(c=>c.loop_factor>.35)}}
function eeaAnalyze(){return{harvest:["fear","neglect","exposure"]}}
function ppmPredict(){return[{id:"p1",via:["n-fear","n-public","n-tariro"],choke:"n-public"},{id:"p2",via:["n-fear","n-rest","n-tariro"],choke:"n-rest"}]}
function isgGenerate(s,note){const ideas=[];for(const n of nimScan(s).weak){ideas.push({type:"reinforce",target:n.id,label:"Strengthen "+n.name});ideas.push({type:"cloak",target:n.id,label:"Cloak "+n.name})}ideas.push({type:"invert_loop",target:"n-fear",label:"Invert fear loop"});ideas.push({type:"decoy",target:"n-public",label:"Rotate decoy"});ideas.push({type:"value_substitute",target:"n-house",label:"Substitute fear with witness"});if(note&&note.trim())ideas.unshift({type:"reinforce",target:"n-tariro",label:"Ingest insight"});return ideas}
async function apply(s,idea){const allowed=["cloak","reinforce","invert_loop","decoy","value_substitute"];if(!allowed.includes(idea.type)){log(s,"BLOCKED","Safeguard refused "+idea.type);return s}const node=s.nodes.find(n=>n.id===idea.target);if(idea.type==="cloak"&&node)node.cloak=Math.min(1,node.cloak+.25);if(idea.type==="reinforce"&&node){node.resilience=Math.min(1,node.resilience+.08);node.vulnerability=Math.max(.05,node.vulnerability-.08)}if(idea.type==="invert_loop")s.circuits.forEach(c=>{if(c.from===idea.target||c.to===idea.target)c.loop_factor=Math.max(0,c.loop_factor-.2)});if(idea.type==="decoy"){s.watch.decoys++;s.packets.push({kind:"DECOY",at:idea.target})}if(idea.type==="value_substitute"&&node)node.resilience=Math.min(1,node.resilience+.05);s.interventions.unshift({...idea,at:new Date().toISOString()});s.chain=await digest(s.chain+idea.label);log(s,"INTERVENTION",idea.label+" · "+idea.type);return s}
function tickWatch(s){s.watch.ticks++;s.watch.decoys++;s.watch.lastTick=new Date().toISOString();log(s,"WATCH","tick "+s.watch.ticks);return s}
window.Aegis={load,save,nimScan,eeaAnalyze,ppmPredict,isgGenerate,apply,tickWatch,log};
