(function(){const KEY="ZIONCORE_SQIE_V2_STATE";const STRATS=["CLOAK","DECOY","DAMP","DECOUPLE","LOOP-INVERT","REINFORCE","CHOKEPOINT","VALUE-SUBSTITUTE"];const ENTITIES=["HEX","CURSE","HOSTILE INTENTION","DARK NODE","SPIRITUAL LOOP","ENERGY SINK","PROTECTION NODE","BLESSING","PRAYER","DIVINE ALIGNMENT","PROPHETIC INPUT"];const $=id=>document.getElementById(id);const uid=p=>p+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,7).toUpperCase();const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const CORE=window.CORE=window.CORE||{version:"2.0",protection:"ARMED",resilience:78,coherence:91,nodes:[],edges:[],protectedNodes:[],strategies:STRATS.map(name=>({id:uid("STR"),name,score:.5+Math.random()*.3})),experiments:[],pioneerLibrary:[],propheticInputs:[],memory:[],interventions:[],audit:[],config:{cycleInterval:12000,mode:"LOCAL"}};
function saveState(){try{localStorage.setItem(KEY,JSON.stringify(CORE))}catch(e){}}
function loadState(){try{const raw=localStorage.getItem(KEY);if(raw)Object.assign(CORE,JSON.parse(raw))}catch(e){}}
function logEvent(type,message){const feed=$("liveFeed");if(feed){feed.insertAdjacentHTML("afterbegin",`<div class=\"feed-line\"><span class=\"feed-time\">${new Date().toLocaleTimeString()}</span> <span class=\"feed-type\">${esc(type)}</span> <span class=\"feed-message\">${esc(message)}</span></div>`);while(feed.children.length>160)feed.lastChild.remove()}const prev=CORE.audit.length?CORE.audit[CORE.audit.length-1].hash:"GENESIS";const hash=btoa(unescape(encodeURIComponent(prev+type+message+Date.now()))).slice(0,48);CORE.audit.push({timestamp:Date.now(),type,message,previous:prev,hash});if(CORE.audit.length>800)CORE.audit=CORE.audit.slice(-800);CORE.memory.unshift(type+": "+message);CORE.memory=CORE.memory.slice(0,120)}
function createSeedNetwork(){if(CORE.nodes.length)return;for(let i=0;i<64;i++)CORE.nodes.push({id:"N"+String(i+1).padStart(3,"0"),type:i<8?"PROTECTION":"MODEL",vulnerability:10+Math.floor(Math.random()*70),resilience:40+Math.floor(Math.random()*55),activity:Math.floor(Math.random()*90),uncertainty:4+Math.floor(Math.random()*28),x:30+Math.random()*840,y:24+Math.random()*400});for(let i=0;i<115;i++){const a=Math.floor(Math.random()*64),b=Math.floor(Math.random()*64);if(a!==b)CORE.edges.push({a,b,weight:+(0.1+Math.random()*0.8).toFixed(3)})}}
function seedFamily(){if(CORE.protectedNodes.length)return;["HRH Saint Tariro Masawi|Self|CORE","HRH Tarry Kupakwashe Masawi|Spouse|CORE","House of Masawi|House|CORE"].forEach(row=>{const [name,relation,level]=row.split("|");CORE.protectedNodes.push({id:uid("PROTECT"),name,relation,level,created:Date.now(),authorised:true})})}
function toast(msg){const el=$("toast");if(!el)return;el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
function drawGraph(id){const svg=$(id);if(!svg)return;const ns="http://www.w3.org/2000/svg";svg.innerHTML="";CORE.edges.slice(0,80).forEach(e=>{const A=CORE.nodes[e.a],B=CORE.nodes[e.b];if(!A||!B)return;const l=document.createElementNS(ns,"line");l.setAttribute("x1",A.x);l.setAttribute("y1",A.y);l.setAttribute("x2",B.x);l.setAttribute("y2",B.y);l.setAttribute("stroke",e.weight>0.7?"#ff607a":"#1aa6c4");l.setAttribute("stroke-opacity","0.45");svg.appendChild(l)});CORE.nodes.forEach(n=>{const c=document.createElementNS(ns,"circle");c.setAttribute("cx",n.x);c.setAttribute("cy",n.y);c.setAttribute("r",n.type==="PROTECTION"?6:4);c.setAttribute("fill",n.vulnerability>60?"#ff607a":n.type==="PROTECTION"?"#e6c36a":"#58e7ff");c.addEventListener("click",()=>inspectNode(n));svg.appendChild(c)})}
function inspectNode(node){const body=$("modalBody");if(body)body.innerHTML=`<pre>${esc(JSON.stringify(node,null,2))}</pre>`;const modal=$("modal")||$("nodeModal");if(modal)modal.classList.add("show");logEvent("NIM","Inspect "+node.id)}
function closeModal(){document.querySelectorAll(".modal,.overlay,#modal").forEach(el=>el.classList.remove("show"))}
function renderProtectionCircle(){const box=$("protectionList");if(!box)return;box.innerHTML=CORE.protectedNodes.map((p,i)=>`<div class=\"item\"><span class=\"badge\">${esc(p.level)}</span> ${esc(p.name)} · ${esc(p.relation)} <button onclick=\"removeProtectedNode(${i})\">remove</button></div>`).join("")||"<div class=notice>No authorised nodes yet.</div>"}
function addProtectedNode(){const name=($("personName")||{}).value?.trim();if(!name){toast("Enter a protected name.");return}CORE.protectedNodes.push({id:uid("PROTECT"),name,relation:($("personRelation")||{}).value||"",level:($("personLevel")||{}).value||"CORE",created:Date.now(),authorised:true});if($("personName"))$("personName").value="";logEvent("PROTECT","Authorised node: "+name);renderAll();saveState()}
function removeProtectedNode(i){const gone=CORE.protectedNodes.splice(i,1)[0];logEvent("PROTECT","Removed "+(gone?.name||i));renderAll();saveState()}
function sense(){logEvent("SENSE","Environmental observation received");CORE.nodes.forEach(n=>n.activity=clamp(n.activity+(Math.random()*8-4),0,100))}
function translate(){logEvent("TRANSLATE","Observations converted to mathematical state")}
function runNIM(){const weak=CORE.nodes.filter(n=>n.vulnerability>60).length;logEvent("NIM","Reassessed "+CORE.nodes.length+" nodes · weak "+weak);return weak}
function runEEA(){const fuels=["FEAR","CONFLICT","ISOLATION"];const pick=fuels[Math.floor(Math.random()*3)];logEvent("EEA","Reinforcement pattern: "+pick+" → FEEDBACK");return pick}
function runPPM(){const paths=5+Math.floor(Math.random()*5);logEvent("PPM",paths+" candidate pathways generated");return paths}
function generateStrategies(){logEvent("ISG",STRATS.length+" intervention strategies generated");return STRATS}
function runSimulation(trials){trials=Number(trials)||1000;logEvent("SIM",trials.toLocaleString()+" simulations initiated");const results=STRATS.map(s=>{let gain=0;const n=Math.min(trials,800);for(let i=0;i<n;i++)gain+=Math.random();return{id:uid("EXP"),strategy:s,trials,resilienceGain:+(gain/n*12).toFixed(2),loopBreak:+(Math.random()*40).toFixed(1),risk:"LOW"}}).sort((a,b)=>b.resilienceGain-a.resilienceGain);CORE.experiments=results.concat(CORE.experiments).slice(0,80);CORE.resilience=clamp(CORE.resilience+Number(results[0].resilienceGain),0,99);logEvent("SIM","Complete · best "+results[0].strategy+" +"+results[0].resilienceGain);logEvent("FLL","Model updated");CORE.interventions.unshift({id:uid("INT"),timestamp:Date.now(),type:results[0].strategy,status:"SIMULATED",outcome:"resilience +"+results[0].resilienceGain});renderAll();saveState();return results}
function runFullCycle(){sense();translate();runNIM();runEEA();runPPM();generateStrategies();runSimulation(400);logEvent("PROTECT","Protective state maintained for "+CORE.protectedNodes.length+" authorised nodes");renderAll();saveState()}
function activateProtection(){CORE.protection="ARMED";logEvent("BROADCAST","Authorised protective output armed. No person targeted.");renderAll();saveState()}
function generatePioneerHypothesis(){const a=STRATS[Math.floor(Math.random()*8)],b=STRATS[Math.floor(Math.random()*8)];const names=["Adaptive Resonance Cloak","Distributed Loop Stabilisation","Multi-layer Protective Mesh","Chokepoint Damp Lattice"];const hypothesis={id:uid("HYP"),name:names[Math.floor(Math.random()*4)]+" v"+(CORE.pioneerLibrary.length+1),genome:[a,b,"observed-vulnerability"],statement:"Combine "+a+" with "+b+".",status:"TESTED",timestamp:Date.now(),score:+(0.4+Math.random()*0.5).toFixed(3)};CORE.pioneerLibrary.unshift(hypothesis);logEvent("PIONEER","New strategy candidate "+hypothesis.name);const box=$("pioneerResult");if(box)box.innerHTML=`<strong>${esc(hypothesis.name)}</strong><br>${esc(hypothesis.statement)}`;renderAll();saveState()}
function mutateStrategy(){const src=CORE.strategies[Math.floor(Math.random()*CORE.strategies.length)];CORE.pioneerLibrary.unshift({id:uid("MUT"),name:"Mutation · "+src.name,genome:[src.name,STRATS[0]],statement:"Synthetic mutation queued.",status:"QUEUED",timestamp:Date.now()});logEvent("PIONEER","Strategy mutation queued");renderAll();saveState()}
function storePropheticInput(){const text=($("propheticText")||{}).value?.trim();if(!text){toast("Enter prophetic input.");return}CORE.propheticInputs.unshift({id:uid("PROP"),text,source:($("propheticSource")||{}).value||"Human input",confidence:Number(($("propheticConfidence")||{}).value)||50,timestamp:Date.now()});if($("propheticText"))$("propheticText").value="";logEvent("PROPHECY","Human spiritual input stored");renderAll();saveState()}
function renderProtectionCircle(){const box=$("protectionList");if(!box)return;box.innerHTML=CORE.protectedNodes.map((p,i)=>`<div class=item>${esc(p.name)} · ${esc(p.relation)}</div>`).join("")}
function renderSpiritualEntities(){const el=$("spiritualEntities")||$("entityList");if(el)el.innerHTML=ENTITIES.map(e=>`<span class=badge>${esc(e)}</span> `).join("")}
function renderStrategies(){const el=$("strategyList")||$("genomeMatrix");if(el)el.innerHTML=CORE.strategies.map(s=>`<div class=matrix-item><b>${esc(s.name)}</b></div>`).join("")}
function renderSimulationTable(){const body=$("simulationTable");if(!body)return;body.innerHTML=CORE.experiments.slice(0,40).map(e=>`<tr><td>${e.id}</td><td>${esc(e.strategy)}</td><td>${e.trials}</td><td>${e.resilienceGain}</td></tr>`).join("")}
function renderNodeTable(){const body=$("nodeTable");if(!body)return;body.innerHTML=CORE.nodes.slice(0,64).map(n=>`<tr><td>${n.id}</td><td>${n.type}</td><td>${n.vulnerability}</td><td>${n.resilience}</td></tr>`).join("")}
function renderPioneerLibrary(){const c=$("pioneerLibrary");if(!c)return;c.innerHTML=CORE.pioneerLibrary.slice(0,30).map(h=>`<div class=item>${esc(h.name)}</div>`).join("")||"<div class=notice>No hypotheses yet.</div>"}
function renderPropheticLedger(){const f=$("propheticLedger");if(f)f.innerHTML=CORE.propheticInputs.slice(0,40).map(p=>`<div class=feed-line>${esc(p.text)}</div>`).join("")}
function renderMemory(){const f=$("modelMemory");if(f)f.innerHTML=CORE.memory.slice(0,80).map(m=>`<div class=feed-line>${esc(m)}</div>`).join("")}
function renderHistory(){const c=$("interventionHistory");if(c)c.innerHTML=CORE.interventions.slice(0,40).map(i=>`<div class=item>${esc(i.type)} · ${esc(i.status)}</div>`).join("")}
function renderAudit(){const f=$("auditFeed");if(f)f.innerHTML=CORE.audit.slice(-80).reverse().map(e=>`<div class=feed-line>${esc(e.type)} ${esc(e.message)}</div>`).join("")}
function renderWatchdog(){const m=$("watchdogMatrix");if(!m)return;m.innerHTML=[["CORE","HEALTHY"],["STORAGE","LOCAL"],["NETWORK",navigator.onLine?"ONLINE":"OFFLINE"],["PROTECTION",CORE.protection]].map(c=>`<div class=matrix-item><small>${c[0]}</small><b>${c[1]}</b></div>`).join("")}
function updateTop(){if($("topProtection"))$("topProtection").textContent=CORE.protection;if($("topResilience"))$("topResilience").textContent=Math.round(CORE.resilience)+"%";if($("topCoherence"))$("topCoherence").textContent=Math.round(CORE.coherence)+"%";if($("topConnectivity"))$("topConnectivity").textContent=navigator.onLine?"ONLINE":"OFFLINE";if($("kNodes"))$("kNodes").textContent=CORE.nodes.length;if($("kEdges"))$("kEdges").textContent=CORE.edges.length;if($("kExperiments"))$("kExperiments").textContent=CORE.experiments.length;if($("kProtected"))$("kProtected").textContent=CORE.protectedNodes.length}
function loadConfiguration(){if($("cycleInterval"))$("cycleInterval").value=CORE.config.cycleInterval;if($("operatingMode"))$("operatingMode").value=CORE.config.mode}
function saveConfiguration(){CORE.config.cycleInterval=Math.max(3000,Number(($("cycleInterval")||{}).value)||12000);CORE.config.mode=($("operatingMode")||{}).value||"LOCAL";saveState();restartAutonomousLoop();toast("Configuration saved.")}
function exportState(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(CORE,null,2)],{type:"application/json"}));a.download="zioncore-sqie-v2-state.json";a.click()}
function importState(){const input=document.createElement("input");input.type="file";input.accept=".json";input.onchange=()=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{Object.assign(CORE,JSON.parse(r.result));saveState();renderAll();toast("Imported")}catch{toast("Invalid JSON")}};r.readAsText(f)};input.click()}
function resetCore(){if(!confirm("Reset local SQIE model?"))return;localStorage.removeItem(KEY);location.reload()}
function verifyAuditChain(){let prev="GENESIS",ok=true;for(const e of CORE.audit){if(e.previous!==prev){ok=false;break}prev=e.hash}toast(ok?"Audit chain valid.":"Audit mismatch.");logEvent("AUDIT",ok?"verification successful":"mismatch")}
function renderAll(){updateTop();renderProtectionCircle();renderSpiritualEntities();renderStrategies();renderSimulationTable();renderNodeTable();renderPioneerLibrary();renderPropheticLedger();renderMemory();renderHistory();renderAudit();renderWatchdog();drawGraph("commandMap");drawGraph("networkMap");loadConfiguration()}
let autonomousTimer=null;function restartAutonomousLoop(){if(autonomousTimer)clearInterval(autonomousTimer);autonomousTimer=setInterval(()=>{if(document.visibilityState!=="visible")return;logEvent("WATCHDOG","Autonomous health sweep");runNIM();runEEA();CORE.resilience=clamp(CORE.resilience+(Math.random()*.5-.15),0,99);updateTop();saveState()},CORE.config.cycleInterval)}
function heartbeat(){if($("topClock"))$("topClock").textContent=new Date().toLocaleTimeString();renderWatchdog()}
function bindNav(){document.querySelectorAll(".nav button").forEach(button=>{button.addEventListener("click",()=>{document.querySelectorAll(".nav button").forEach(b=>b.classList.remove("active"));button.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));const target=document.getElementById(button.dataset.view);if(target)target.classList.add("active");renderAll()})})}
function initialise(){loadState();createSeedNetwork();seedFamily();bindNav();renderAll();logEvent("BOOT","ZionCore SQIE v2 brains online");logEvent("SCOPE","Simulation boundary: no person is targeted");restartAutonomousLoop();fetch("./data/aegis-state.json").then(r=>r.ok?r.json():null).then(d=>{if(d)logEvent("WATCHDOG","Scheduled watch file present")}).catch(()=>{});if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{})}
Object.assign(window,{CORE,addProtectedNode,removeProtectedNode,inspectNode,closeModal,sense,translate,runNIM,runEEA,runPPM,generateStrategies,runSimulation,runFullCycle,activateProtection,generatePioneerHypothesis,mutateStrategy,storePropheticInput,exportState,importState,resetCore,saveConfiguration,verifyAuditChain,renderAll,initialise});
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initialise);else initialise();
setInterval(heartbeat,1000);
})();
