const A=window.Aegis;let S=A.load();
if(!S.family||!S.family.length){S.family=[{name:"HRH Saint Tariro Masawi",rel:"Self",consent:true},{name:"HRH Tarry Kupakwashe Masawi",rel:"Spouse",consent:true},{name:"House of Masawi",rel:"House",consent:true}]}
const map=document.getElementById("map");const ctx=map.getContext("2d");let packets=[];
function size(){map.width=map.clientWidth*devicePixelRatio;map.height=map.clientHeight*devicePixelRatio}
function pos(n){return{x:n.x*map.width,y:n.y*map.height}}
function draw(){size();ctx.clearRect(0,0,map.width,map.height);for(const c of S.circuits){const a=S.nodes.find(n=>n.id===c.from),b=S.nodes.find(n=>n.id===c.to);if(!a||!b)continue;const pa=pos(a),pb=pos(b);ctx.strokeStyle=c.loop_factor>.4?"rgba(196,91,91,.7)":"rgba(126,224,214,.35)";ctx.lineWidth=(c.loop_factor>.4?2.4:1.2)*devicePixelRatio;ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke()}for(const n of S.nodes){const p=pos(n),r=(11+n.resilience*12)*devicePixelRatio;ctx.beginPath();ctx.fillStyle=n.vulnerability>.45?"#c45b5b":(n.cloak>.2?"#7ee0d6":"#d4b36a");ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.fillStyle="#f3eee4";ctx.font=(12*devicePixelRatio)+"px Georgia";ctx.fillText(n.name,p.x+r+6,p.y)}for(const pk of packets){ctx.beginPath();ctx.fillStyle="#d4b36a";ctx.arc(pk.x,pk.y,4*devicePixelRatio,0,Math.PI*2);ctx.fill()}}
function paintFamily(){document.getElementById("famTable").innerHTML=S.family.map((f,i)=>`<tr><td>${f.name}</td><td>${f.rel}</td><td>${f.consent?"yes":"no"}</td><td><button class="ghost" data-del="${i}">Remove</button></td></tr>`).join("");document.querySelectorAll("[data-del]").forEach(btn=>btn.onclick=()=>{S.family.splice(+btn.dataset.del,1);A.save(S);paint()})}
function paint(){draw();const scan=A.nimScan(S),eea=A.eeaAnalyze(),paths=A.ppmPredict();document.getElementById("mWatch").textContent=S.watch.ticks;document.getElementById("mFamily").textContent=S.family.length;document.getElementById("mDecoy").textContent=S.watch.decoys;document.getElementById("mChain").textContent=String(S.chain||"GENESIS").slice(0,8);const hrs=A.staleHours(S);document.getElementById("stale").textContent=hrs>12?"Watch is stale. Run WATCH TICK or wait for the six-hour Action.":"Watch is fresh. The Action continues when this tab is closed.";document.getElementById("mods").innerHTML=`<div class="mod"><b>NIM</b><br>weak ${scan.weak.length} · potholes ${scan.potholes.length} · loops ${scan.loops.length}</div><div class="mod"><b>EEA</b><br>${eea.harvest.join(", ")}</div><div class="mod"><b>PPM</b><br>${paths.map(p=>p.id+" choke "+p.choke).join(" · ")}</div><div class="mod"><b>FLL</b><br>${S.feed.length} events · ${S.family.length} protected</div>`;document.getElementById("economy").innerHTML=Object.entries(A.PROTOCOLS).map(([k,v])=>`<div class="item"><span class="badge">${k}</span>${v}</div>`).join("");document.getElementById("feed").innerHTML=S.feed.map(f=>`<div class="item"><span class="badge">${f.type}</span>${f.summary}</div>`).join("")||"No events.";const ideas=A.isgGenerate(S);document.getElementById("ideas").innerHTML=ideas.slice(0,6).map((x,i)=>`<button data-i="${i}">${x.label}</button>`).join("");document.querySelectorAll("#ideas button").forEach((b,i)=>b.onclick=async()=>{S=await A.apply(S,ideas[i]);A.save(S);paint()});paintFamily()}
map.addEventListener("click",e=>{const rect=map.getBoundingClientRect();const x=(e.clientX-rect.left)*devicePixelRatio,y=(e.clientY-rect.top)*devicePixelRatio;let hit=null,best=1e9;for(const n of S.nodes){const p=pos(n),d=Math.hypot(p.x-x,p.y-y);if(d<best){best=d;hit=n}}if(hit&&best<48*devicePixelRatio)document.getElementById("inspect").textContent=hit.name+" · res "+hit.resilience.toFixed(2)+" · vul "+hit.vulnerability.toFixed(2)+" · cloak "+(hit.cloak||0).toFixed(2)});
document.getElementById("addFam").onclick=()=>{const name=document.getElementById("famName").value.trim();if(!name)return;S.family.push({name,rel:document.getElementById("famRel").value,consent:true});document.getElementById("famName").value="";A.log(S,"FAMILY","Now protecting "+name);A.save(S);paint()};
document.getElementById("packBtn").onclick=()=>{S=A.familyPack(S);A.save(S);paint()};
document.getElementById("scanBtn").onclick=()=>{A.log(S,"SCAN","Sweep for "+S.family.length+" protected");A.save(S);paint()};
document.getElementById("tickBtn").onclick=async()=>{S=await A.tickWatch(S);A.save(S);paint()};
document.getElementById("cloakBtn").onclick=async()=>{S=await A.tickWatch(S);A.save(S);paint()};
document.getElementById("ingestBtn").onclick=()=>{A.log(S,"INSIGHT",document.getElementById("insight").value.slice(0,120)||"empty");A.save(S);paint()};
["prayBtn","restBtn","ateBtn"].forEach(id=>{const el=document.getElementById(id);if(el)el.onclick=()=>{S=A.attest(S,id.replace("Btn","").replace("pray","prayed").replace("rest","rested").replace("ate","ate"));A.save(S);paint()}});
document.getElementById("snapBtn").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:"application/json"}));a.download="aegis-snapshot.json";a.click()};
document.getElementById("auditBtn").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([S.feed.map(f=>f.at+" "+f.type+" "+f.summary).join("\n")],{type:"text/plain"}));a.download="aegis-audit.txt";a.click()};
document.getElementById("simBtn").onclick=()=>{const path=A.ppmPredict()[0];const nodes=path.via.map(id=>S.nodes.find(n=>n.id===id)).filter(Boolean);if(nodes.length<2)return;let t=0;const timer=setInterval(()=>{t+=0.02;if(t>=nodes.length-1){clearInterval(timer);packets=[];paint();return}const i=Math.floor(t),f=t-i,a=pos(nodes[i]),b=pos(nodes[i+1]);packets=[{x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f}];draw()},30);A.log(S,"SIM","Model packet on "+path.id);A.save(S);paint()};
fetch("./data/aegis-state.json").then(r=>r.ok?r.json():null).then(remote=>{if(remote?.watch?.ticks>(S.watch.ticks||0)){S.watch=Object.assign(S.watch,remote.watch);A.log(S,"WATCH","Loaded scheduled file");A.save(S)}}).catch(()=>{}).finally(paint);
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
setInterval(async()=>{S=await A.tickWatch(S);A.save(S);paint()},180000);
